### ISSUE TITLE
There is no `build` directory

### ISSUE THREAD

**Issue by bpow** [NimbleGen/bioinformatics#151]
`documentation/COMMAND_LINE_BUILD.md` refers to the directory `bioinformatics/build/heatseq_commandline`, but there is no `build` directory in the repository or in the source tgz or zip file for the version 1.0 release. Is this supposed to refer to `bioinformatics/nimblegen_heatseq_build/hsqutils_commandline`, or is that for a different build for just one component of the tooling?

**Comment by heilmank** [comment]
Mr. Powell,

You are correct,
*bioinformatics/nimblegen_heatseq_build/hsqutils_commandline* is the
correct path.  Thanks for letting us know that the documentation was
incorrect.  I've updated section 5 of the COMMAND_LINE_BUILD.md file to
reflect the current state of the build process.  Let me know if you run
into any additional problems or have any questions regarding HSQUtils.
Thanks again.

Kurt Heilman
Software Engineer
Roche Sequencing Solutions
500 South Rosa Road
Madison, WI 53719
